### ISSUE TITLE
Actuator /actuator endpoint contains links to disabled spring-cloud-context actuator endpoints

### ISSUE THREAD

**Issue by maxromanovsky** [spring-cloud/spring-cloud-commons#109]
HATEOAS `/actuator` endpoint renders `spring-cloud-context` endpoints even if they are disabled (`actuator.*.enabled=false` in `application.properties`). [Build-in endpoints](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints) are not rendered if disabled.
Originally I've added an issue https://github.com/spring-projects/spring-boot/issues/5389 to the Spring Boot itself, but now, trying to create minimal project reproducing it, I've figured out that it's Spring Cloud-specific.

Example:

```
endpoints.pause.enabled=false
endpoints.refresh.enabled=false
```

but the `/actuator` endpoint contains them. Excerpt from output:

```json
{
    "_links": {
        "pause": {
            "href": "http://localhost:8080/pause"
        },
        "refresh": {
            "href": "http://localhost:8080/refresh"
        }
    }
}
```

**Comment by dsyer** [comment]
Interestingly, this is semi-intentional because endpoints can always be enabled at runtime, so it is better to provide the resource and make it send a "disabled" response, but I can see why it arguably should be otherwise. Ultimately we should be consistent with Spring Boot, but I'm not really willing to make the change here right now. Perhaps the Spring Boot issue should be re-opened.

**Comment by maxromanovsky** [comment]
@dsyer I've re-opened the original issue. Thanks for the feedback!
