### ISSUE TITLE
Error ReactiveLoadBalancer$Factory that could not be found

### ISSUE THREAD

**Issue by neon-paradise** [spring-cloud/spring-cloud-commons#1114]
I have a question.
Perhaps add the `@ConditionalOnBean(LoadBalancerClientFactory.class)` condition to the `BlockingLoadBalancerClientAutoConfiguration.BlockingLoadBalancerRetryConfig` class to avoid this error?
`Parameter 0 of method loadBalancedRetryFactory in org.springframework.cloud.loadbalancer.config.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerRetryConfig required a bean of type 'org.springframework.cloud.client.loadbalancer.reactive.ReactiveLoadBalancer$Factory' that could not be found.`

I was running the microservice locally with spring.cloud.loadbalancer.enabled=false. The `@ConditionalOnClass(RetryTemplate.class)` condition passes, because spring-kafka is present in the dependencies.
I had to add BlockingLoadBalancerClientAutoConfiguration to exclude in @SpringBootApplication. Or is this the right way to solve the problem?

Dependencies:
spring-boot-dependencies 2.6.7
spring-cloud-dependencies 2021.0.2

**Comment by OlgaMaciaszek** [comment]
Hello, @neon-paradise please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by norbson** [comment]
Hello,

I believe this issue is still there. Here is a code reproducing the problem https://github.com/norbson/demo

It is plain project generated by initializer with spring-retry added.

One way to reproduce problem:
1. disable loadbalancer (spring.cloud.loadbalancer.enabled=false)
2. spring-retry on classpath

Effect:
APPLICATION FAILED TO START
_Parameter 0 of method loadBalancedRetryFactory in org.springframework.cloud.loadbalancer.config.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerRetryConfig required a bean of type 'org.springframework.cloud.client.loadbalancer.reactive.ReactiveLoadBalancer$Factory' that could not be found._

Potential Cause:
Configuration/conditions of BlockingLoadBalancerRetryConfig class.

**Comment by OlgaMaciaszek** [comment]
Sorry, @norbson, haven't noticed the sample - will take a look. Btw., I've just realised it's you :wave:

**Comment by Zhen-Yee** [comment]
Hi @OlgaMaciaszek, 

I was updating our dependencies in our project, one of which was spring-cloud-dependencies version from 2020.0.3 to 2021.0.1 and I encountered the same issue. I see that it's `In Progress`, would you happen to have an ETA on a fix for this issue?

Thank you!
