### ISSUE TITLE
Why loadbalancer implement of RestTemplateCustomizer is @ConditionalOnMissingBean

### ISSUE THREAD

**Issue by SkyeBeFreeman** [spring-cloud/spring-cloud-commons#1138]
https://github.com/spring-cloud/spring-cloud-commons/blob/656aeaa0236e933df4bf68275a633b262d405324/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java#L89

If I create another `RestTemplateCustomizer`, this bean will not be instantiated and `RestTemplate` can't do load balance.

**Comment by OlgaMaciaszek** [comment]
Hello @SkyeBeFreeman , that is because it is not `org.springframework.boot.web.client.RestTemplateCustomizer`, but `org.springframework.cloud.client.loadbalancer.RestTemplateCustomizer` which is a specific LB-related interface that the users are supposed to implement if they want to purposefully modify that behaviour.

**Comment by SkyeBeFreeman** [comment]
@DerekYRC it seems that you used a wrong `RestTemplateCustomizer ` before.

**Comment by DerekYRC** [comment]
@OlgaMaciaszek @SkyeBeFreeman Thanks a lot. Have a good day :)
