### ISSUE TITLE
Incorrect server.port from inactive profile is applied when having spring-cloud-starter-bootstrap as a dependency

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-commons#1177]
I'm upgrading a Spring Boot application to the new 3.x version. I dependended on a few spring-cloud projects so I also updated them pointing at 2022.0.0-RC3.

As a sidenote: I was surprised that the `bootstrap.yml` file was being ignored. I had to manually add the dependency with `spring-cloud-starter-bootstrap`. It wasn't necessary with 2021.x.x was it? I think it was a transitive dependency. Has this changed on purpose?

Consider this bootstrap.yml:

```
spring:
  application:
    name: boot3cloud

logging:
  level:
    org.springframework.web: info

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: alt

logging:
  level:
    org.springframework.web: debug

server:
  port: 9696
```

If I start the application with no profile selected or the local profile, the default server.port should be 8080. However, the alt profile server.port is incorrectly being applied:

```
 :: Spring Boot ::                (v3.0.0)

2022-12-03T20:47:22.672+01:00  INFO 66426 --- [           main] c.e.b.Boot3profileApplicationKt          : The following 1 profile is active: "local"
2022-12-03T20:47:23.139+01:00  INFO 66426 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=70415907-40e8-328a-96ef-8fd2f45c0e3b
2022-12-03T20:47:23.592+01:00  INFO 66426 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-12-03T20:47:23.936+01:00  INFO 66426 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 9696
2022-12-03T20:47:23.953+01:00  INFO 66426 --- [           main] c.e.b.Boot3profileApplicationKt          : Started Boot3profileApplicationKt in 2.038 seconds (process running for 2.586)
```

Notice it only wrongly applied the server.port=9696, but the logging.level.org.springframework.web is correct (info, instead of debug).

if I remove the `spring-cloud-starter-bootstrap` dependency and move the config to application.yml it behaves as expected (8080 as the default port when alt profile is not selected).

**Sample**
https://github.com/codependent/boot3profile

**Comment by ryanjbaxter** [comment]
Does this happen when using Spring Cloud 2021.0.5?

**Comment by ryanjbaxter** [comment]
Here is what is happening.

In Spring Cloud 2022 we changed how we are processing bootstrap.yaml to use `BootstrapConfigFileApplicationListener`.  This code was take from Spring Boot 2.7.x.  In Boot 2.7.x the code was only used when `spring.config.use-legacy-processing` was `true`, which means it only new how to separate documents by profiles using `spring.profiles` and had no idea about `spring.config.activate.on-profile`.  The problem is that if you have configuration that uses `spring.profiles` in Boot 3.0.x the application will fail to start because `spring.profiles` is no longer supported so Boot throws an exception.

We need to update `BootstrapConfigFileApplicationListener` so it now uses `spring.config.activate.on-profile` instead
