### ISSUE TITLE
Cloud-config doesn't work properly in application with several child contexts

### ISSUE THREAD

**Issue by kiril-akshonau** [spring-cloud/spring-cloud-commons#190]
Hi guys.

We have dedicated cloud-config-server application and one REST application with several child spring contexts inside. After update to newest spring-cloud-config version we've faced with issue: property placeholders in second and further child contexts became unresolvable.
I've prepared [project](https://github.com/kiril-akshonau/cloud-config-test) with example for you.
_How to reproduce:_ 
1.  Start config server: `gradlew bootRunConfig`
2.  Start main application: `gradlew bootRunApp`

_Expected:_
1. http://localhost:8081/ping returns `pong from app1`
2. http://localhost:8082/ping returns `pong from app2`

_Actual:_
Main application throws
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'foo.app2.pong' in value "${foo.app2.pong}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174) ~[spring-
core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
..........
```

_Workaround:_
I've noticed that I can define old version of `org.springframework.cloud:spring-cloud-context:1.1.7.RELEASE` in `build.gradle`. With 1.1.7 everything works as expected.
I think this is connected somehow with this [fix](https://github.com/spring-cloud/spring-cloud-commons/commit/331e79002620f458f2ae4b51af8147242e700af1#diff-ffd4ed2e59b54e6acb4b4f3a088f9e31)

**Comment by spencergibb** [comment]
That's not multiple child contexts, that's multiple spring-boot applications. That's fairly unusual. Why are you doing that? /cc @dsyer

**Comment by dsyer** [comment]
It was sort of accidental that it worked before. In 1.1.8 you have a sensible and predictable application context hierarchy:

```
     bootstrap
           |
        parent
       /          \
    app1     app2
```

So there is only one bootstrap context, and hence only one config client. You want app1 and app2 to have separate identities and separate bootstrap contexts, so you need to launch them as separate contexts, not as siblings.

In 1.1.7 you would have had this:

```
   bootstrap(app2)
          |
   bootstrap(app1)
          |
     bootstrap
           |
        parent
       /          \
    app1     app2
```

which is kind of crazy (there's no real parent child relation between bootstrap(app1) and app2), so that's what the change you identified fixed.

For now at least, you can launch your two apps as separate contexts (no common parent). I'll have a think about whether there is a way for them to share a parent, and what that would even mean. Maybe you could help by explaining why you think you need a common parent?

A possible downside of the 1.1.8 implementation is that the bootstrap initializers are actually only applied to the parent. That works out fine in practice for most use cases, because most initializers only modify the `Environment` or add beans to the context, and both are then available to child contexts through the hierarchy.

**Comment by kiril-akshonau** [comment]
@dsyer Thanks for explanations and fix. We'll think about separating application into independent boot applications.

**Comment by Siarhei-Yarkavy** [comment]
Thank you for the fix, we were affected by this issue either.
