### ISSUE TITLE
eclipse maven import problem

### ISSUE THREAD

**Issue by jibijose** [spring-cloud/spring-cloud-commons#31]
Since we have two maven projects "spring-cloud-commons/pom.xml" and "spring-cloud-commons/spring-cloud-commons/pom.xml", eclipse import will fail since projects with same name cannot co-exist.

Solution: Rename one project.

**Comment by dsyer** [comment]
Is eclipse using the directory name? You can always change the name of the top level directory.

**Comment by mbenson** [comment]
@jibijose: Are you using m2eclipse? My experience is that the projects are imported by their Maven project names, rather than by their directory names, therefore the project described by `spring-cloud-commons/pom.xml` imports as `spring-cloud-commons-parent` and the project described by `spring-cloud-commons/spring-cloud-commons/pom.xml` imports as `spring-cloud-commons`. I think this is a non-issue.
