### ISSUE TITLE
value starts with {cipher} in customized PropertySourceLocator do not get decrypted

### ISSUE THREAD

**Issue by ktong** [spring-cloud/spring-cloud-commons#54]
from spring-cloud/spring-cloud-config#209

**Comment by ktong** [comment]
It probably caused by PropertySourceBootstrapConfiguration is after EnvironmentDecryptApplicationInitializer

**Comment by ktong** [comment]
It's duplicated with spring-cloud/spring-cloud-config#30

**Comment by dsyer** [comment]
I don't think that's the same as https://github.com/spring-cloud/spring-cloud-config/issues/30 (which is about `@PropertySource`). This one is quite deep and not at all easy to address (even if we fix the ordering problem). The issue is that the config server does decryption as well, and we don't want a local decryptor to decrypt something and get it wrong, and then override the value from the server. So it's a delicate matter: who has the last say on property values?
