### ISSUE TITLE
ConfigurationPropertiesRebinder can't reset remove config bean filelds

### ISSUE THREAD

**Issue by fudali113** [spring-cloud/spring-cloud-commons#818]
https://github.com/spring-cloud/spring-cloud-commons/blob/f58895373b89b7f43c891f4f0b9fefa8e48b0187/spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java#L105

@ConfigurationProperties bean if has one value, i change config to remove filed value, this case bean filed value not refresh, not my expected！

any solution for this case ?

**Comment by fudali113** [comment]
@spencergibb need help？i can impl this feature。

i will use `BeanUtils.copyPropties(BeanUtils.instantiateClass(beanType), bean)` reset bean fields;


and i suggest rebind will use event keys rebind part of the `ConfigPropertiesBean`，not all beans

**Comment by ryanjbaxter** [comment]
I was just looking at this.

If I remove the property and then refresh, I see a similar behavior where the property value is not changed.

The version of `ConfigurationPropertiesRebinder` you linked to above is quite old.  What version of Spring Cloud are you using?

As always, we are happy to have PRs from the community, so if you have an idea on how to make this work please submit a PR.

**Comment by ryanjbaxter** [comment]
Also I assume the problem is that you are removing the property completely and not just removing the value, correct?

**Comment by ryanjbaxter** [comment]
When we remove the property there is no longer a property to update in the bean when the refresh occurs.  The property needs to be present in order to the `JavaBeanBinder` to set the value.  With the property missing, no update will occur.
https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/JavaBeanBinder.java#L92

https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/Binder.java#L369

https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/Binder.java#L418

**Comment by fudali113** [comment]
> I was just looking at this.
> 
> If I remove the property and then refresh, I see a similar behavior where the property value is not changed.
> 
> The version of `ConfigurationPropertiesRebinder` you linked to above is quite old. What version of Spring Cloud are you using?
> 
> As always, we are happy to have PRs from the community, so if you have an idea on how to make this work please submit a PR.

i use 2.0.1.REALEASE & 1.2.0 RC ;

They all have that problem

**Comment by fudali113** [comment]
> Also I assume the problem is that you are removing the property completely and not just removing the value, correct?

yes

**Comment by fudali113** [comment]
> When we remove the property there is no longer a property to update in the bean when the refresh occurs. The property needs to be present in order to the `JavaBeanBinder` to set the value. With the property missing, no update will occur.

i know this logic，but i think it`s unreasonable.

When we remove the properties on the remote configuration server, this change should be synchronized to the application, but not synchronized;

**Comment by spencergibb** [comment]
The trouble is that's all in spring boot. You could, rather than checking on the absence of a property, check one that disables something when set to false.

**Comment by fudali113** [comment]
> > When we remove the property there is no longer a property to update in the bean when the refresh occurs. The property needs to be present in order to the `JavaBeanBinder` to set the value. With the property missing, no update will occur.
> 
> i know this logic，but i think it`s unreasonable.
> 
> When we remove the properties on the remote configuration server, this change should be synchronized to the application, but not synchronized;

in this case

**Comment by fudali113** [comment]
> The trouble is that's all in spring boot. You could, rather than checking on the absence of a property, check one that disables something when set to false.

This is also a solution, but requires users to adhere to the convention。

**Comment by fudali113** [comment]
in the offline abTest case：

support remove flow:

`remove the key -> delete code & redeploy`

check enable flow:

`change enable to false -> delete code & redeploy -> remove the key`

**Comment by spencergibb** [comment]
Sometimes adhering to a convention for a maybe little used feature is better than the additional maintenance burden of trying to work around spring boot functionality

**Comment by fudali113** [comment]
> Sometimes adhering to a convention for a maybe little used feature is better than the additional maintenance burden of trying to work around spring boot functionality

i think this case not spring boot issue

`ConfigurationPropertiesBindingPostProcessor` just bind fields in source，because maybe other `BeanPostProcessor` set bean fields；
`so should be reinit fields on rebinder，rebinder is rebind starting point，rebinder knows if the bean needs to be reinitialized`

**Comment by ryanjbaxter** [comment]
@fudali113 
this is all we currently do
https://github.com/spring-cloud/spring-cloud-commons/blob/2.2.x/spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java#L105-L108

We pretty much rely on Boot and Framework to handle updating the Bean values and the logic that is currently there relies on the presence of the property key to do that. 

You really have three options to make your use case work.

1. Instead of relying on the absence a value to trigger whatever logic you are trying to enable rely on the presence of a value
2. Just remove the value of the key and leave the key in the properties file
3.  Remove the key and value and redeploy the app
