### ISSUE TITLE
Any plans to support more load balance ruls?

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud/spring-cloud-commons#836]
Like Ribbon, it supports ruls as follows
- RoundRobin (supported)
- Retry (supported?)
- ZoneAffinity (supported?)
- Random
- ResponseTimeWeighted

And more

and others load balance rule like Apache Dubbo as follows
- LeastActiveLoadBalance
- ConsistentHashLoadBalance
- RandomWeightLoadBalance

But for me, the important features are
- support Predicate to filter customization server instances like Ribbon
```java
public interface Predicate<T> extends java.util.function.Predicate<T> {
  boolean apply(@Nullable T input);
}
```
- support composite Rules and Predicates

Thanks a lot

**Comment by OlgaMaciaszek** [comment]
Hi, @HaojunRen the only other implementation that we have currently in the backlog is [this one](https://github.com/spring-cloud/spring-cloud-commons/issues/601), which will most probably use failures, response time and load-metrics.

As we felt that some Ribbon rules were used unproportionately more often than other ones, we have decided to start with an MVP approach and go adding implementations as we got requests from the community (that's how we have added Zone Affinity and Health-Check load-balancing, for example). If you would like to see any of these rules in particular implemented because you were using it with Ribbon and you would like to use it in your projects, please create a separate GH issue per such a rule/ use-case, we'll collect votes from the community, discuss it with the team and take it from there.

**Comment by HaojunRen** [comment]
@OlgaMaciaszek Thanks for your answer. will sc 2020 still be compatible with ribbon? That means if I import ribbon jar in 2020 manually, ribbon would still work or not?

**Comment by spencergibb** [comment]
No it will not. Ribbon support has been removed as we planned and announced previously
