### ISSUE TITLE
split packages in spring-cloud-commons prevents usage of java modules when reactor core is used

### ISSUE THREAD

**Issue by amtineo** [spring-cloud/spring-cloud-commons#887]
**Describe the bug**
When using the java module system, there are split packages between the **reactor core** library and **spring-cloud-commons**. This prevents the system from loading the modules since it violates the package rule. 

The following error is thrown when attempting to start a spring boot application:

 ```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules reactor.core and spring.cloud.commons export package reactor.core.publisher to module spring.boot.starter.actuator
```
**Sample**
Create a project with the following dependencies:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starer-web</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-cloud-discovery</artifactId>
</dependency>
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.4.2</version>
</dependency>
```
Define the required modules in `module-info.java`:
```
requires spring.web;
requires spring.boot;
requires spring.boot.autoconfigure;
requires spring.boot.starter.web;
requires spring.boot.starter.tomcat;
requires spring.boot.starter.actuator;
requires org.apache.tomcat.embed.core;
requires org.apache.tomcat.embed.websocket;
requires com.fasterxml.jackson.databind;

requires reactor.core;

exports my.personal.beans;

opens my.personal.beans to spring.core;
```

Possible solution:

Rename the package `reactor.core.publisher` from `spring-cloud-commons` so it doesn't conflict with the same package name found in the `reactor core` library

**Comment by spencergibb** [comment]
Unfortunately, it uses package protected class is `reactor.core.publisher`.

There's a [note](https://github.com/spring-cloud/spring-cloud-commons/commit/7033a9877f4f7ed879c6cd5dbb5dbfbe81118368#diff-cae98f54326b209e094628d030e65c7f1c6f5b0f2d9bebdf25e09daa4407a1d8R22) that this functionality will be moved to reactor and can then be removed here. @TYsewyn and @simonbasle would need to give us an update.

**Comment by simonbasle** [comment]
> Unfortunately, it uses package protected class is `reactor.core.publisher` so it can't just be renamed.
> 
> There's a [note](https://github.com/spring-cloud/spring-cloud-commons/commit/7033a9877f4f7ed879c6cd5dbb5dbfbe81118368#diff-cae98f54326b209e094628d030e65c7f1c6f5b0f2d9bebdf25e09daa4407a1d8R22) that this functionality will be moved to reactor and can then be removed here. @TYsewyn and @simonbasle would need to give us an update.

If the only package-protected classes are the implemented interfaces like `SourceProducer`, it should be possible to do without them (although it would probably imply at least replacing these occurrences by the interface(s) they themselves extend).

That said, from 3.4.0 onwards we now have `Flux.firstWithValue`, would that fit the bill @TYsewyn @spencergibb ?

**Comment by TYsewyn** [comment]
I’d need to look into that (new?) functionality.
In any case, I should have fixed this some time ago.
I’ll check this later today.

**Comment by TYsewyn** [comment]
@spencergibb, we'll have to discuss if `Flux.firstWithValue` might make sense for us.
There's a small but very distinct difference between the 2 constructions.
Where `Flux.firstWithValue` is only taking the `onNext` (so first value) into account, `CloudFlux.firstNonEmpty` is also taking the first `onError` signal into account.
I believe this was set up to have a "fail fast" approach, rather than waiting for the first `DiscoveryClient` who would respond to the `getInstances` call in case you have multiple discovery clients configured.
If it doesn't fit our use case (or we want to support both using a flag, maybe?) I'll move that piece of functionality over to Reactor @simonbasle

**Comment by simonbasle** [comment]
are we sure that the same cannot be achieved by composing some operators over the sources in `Flux.firstWithSignal`?
I guess that if you had to add this custom operator, it was because the `first` (now `firstWithSignal`) also shortcuts on _empty_ sources, and as a consequence I'm assuming that such empty sources can happen for `DiscoveryClient`?

But if that is the case, could `switchIfEmpty(Mono.delay(d).then(Mono.empty()))` work to protect against such sources?

The idea being that `d` is set high enough (typically congruent with a `.timeout`) that other sources have a chance to resolve or error faster. The downside being that if ALL sources are empty, then the request will take `d` to produce nothing (but again, I expect a timeout after that).

**Comment by spencergibb** [comment]
So just doing the following
```
+++ b/spring-cloud-commons/src/main/java/reactor/core/publisher/FluxFirstNonEmptyEmitting.java
@@ -30,7 +30,7 @@ import reactor.util.annotation.Nullable;
 /**
  * @author Tim Ysewyn
  */
-final class FluxFirstNonEmptyEmitting<T> extends Flux<T> implements SourceProducer<T> {
+final class FluxFirstNonEmptyEmitting<T> extends Flux<T> implements Scannable, Publisher<T> {
 
        final Publisher<? extends T>[] array;
 
@@ -131,6 +131,11 @@ final class FluxFirstNonEmptyEmitting<T> extends Flux<T> implements SourceProduc
                return null; // no particular key to be represented, still useful in hooks
        }
 
+       @Override
+       public String stepName() {
+               return "source(" + getClass().getSimpleName() + ")";
+       }
+
  ```
and `FluxFirstNonEmptyEmittingTests` all pass.

Is that sufficient for now and we can change the package?

**Comment by spencergibb** [comment]
Looks like we're dependent on other package private interfaces :-(

**Comment by spencergibb** [comment]
That test suite is good because just switching naively to `Flux.firstWithSignal()` fails two tests.
